#
# .travis.yml
# https://travis-ci.com/plans
#

language: c

sudo: false

compiler:
  - gcc

addons:
  apt:
    packages:
    - autopoint
    - gettext

script: |
        cd urjtag 
        ./autogen.sh
        make

# l l
