#
# .travis.yml
# https://travis-ci.com/plans
#

language: c
compiler:
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y autopoint

script: |
        cd urjtag 
        ./autogen.sh
        make

# l l
